### ISSUE TITLE
这个请求一直超时

### ISSUE THREAD

**Issue by yezige** [EvanNotFound/vercount#12]
https://events.vercount.one/log?jsonpCallback=VisitorCountCallback 

![image](https://github.com/user-attachments/assets/03ba52e2-039b-437e-a05c-8b240418d066)

**Comment by EvanNotFound** [comment]
你的网络问题，因为 vercount 部署在 vercel 上，你的网络墙了 vercel 吧

**Comment by yezige** [comment]
我觉得也是，有可用的cdn吗？

**Comment by EvanNotFound** [comment]
我没有备案的域名😂
