### ISSUE TITLE
希望可以尽快出一个重置或设置访问量的功能

### ISSUE THREAD

**Issue by Jason-JP-Yang** [EvanNotFound/vercount#2]
我自己的Blog被我同学**恶意POST**：
![image](https://github.com/EvanNotFound/vercount/assets/108601445/3eb69cdf-9af4-4455-a4d8-2a33cc8222b5)
_**View count of 951623**_
显示的数目极其离谱，目前我都没有找到合适的方法解决问题
希望可以对每个接入api的网站都分配SSH (or key)以管理自己的View counts

**Comment by Jason-JP-Yang** [comment]
还有希望可以利用website fingerprint 和User Agent两项技术同时来分辨是不是同一个访问者，UA是可以被伪造的，Fingerprint很难进行伪造 ，而且IP也是可以被VPN伪造的（而且也是动态的?），Fingerprint可能是更合理的计算方法？

**Comment by Jason-JP-Yang** [comment]
Links:
https://github.com/Jason-JP-Yang/Blog

**Comment by Jason-JP-Yang** [comment]
额，甚至昨晚ip一度被ban掉了...........HTTPS FETCH IN 402 ERROR

**Comment by EvanNotFound** [comment]
我去原来是你，昨天我流量爆炸

**Comment by EvanNotFound** [comment]
更改数据可以加我微信 me.ohevan.com
