### ISSUE TITLE
已集成到个人博客，并已推荐

### ISSUE THREAD

**Issue by Farb** [EvanNotFound/vercount#5]
已集成到个人博客，并已推荐、star.

不知道是不是服务不太稳还是啥原因，有时发现数据一直loading

https://farb.github.io/p/hugo_stack_vercount/

**Comment by EvanNotFound** [comment]
谢谢支持

**Comment by Farb** [comment]
> 谢谢支持

最近一直处于loading状态啊，感觉用不了了啊
