### ISSUE TITLE
如何重置接口自带的访问量

### ISSUE THREAD

**Issue by resetsix** [EvanNotFound/vercount#6]
在hexo主题文件的`_config.yml` footer 中贴入以下代码，但会显示自带的访问量（几百万那种）。请问是需要自己部署吗还是有其他的重置方法

> 目前只在 localhost 测试过

<img width="569" alt="图片" src="https://github.com/EvanNotFound/vercount/assets/85431995/68fe48d2-1eb3-486e-8e92-87829f1a2ca3">

**Comment by criwits** [comment]
几百万那个是因为不蒜子上 localhost 域名的访问量巨大（大量用户测试时使用的 localhost 域名数据都被统计了 XD），部署到自己域名上数据应该就正常了。

**Comment by resetsix** [comment]
> 几百万那个是因为不蒜子上 localhost 域名的访问量巨大（大量用户测试时使用的 localhost 域名数据都被统计了 XD），部署到自己域名上数据应该就正常了。

明白了感谢
