### ISSUE TITLE
统计数据出现极其离谱的数字

### ISSUE THREAD

**Issue by yoghurtlee-thu** [EvanNotFound/vercount#8]
如题。我大概在半个月前引入了 JavaScript，但是并没有插入展示访问量的 HTML。

最近在本地测试的时候，发现访问数据高得离谱：

<img width="903" alt="image" src="https://github.com/EvanNotFound/vercount/assets/146422759/9ca2118b-efb7-4a9d-ba73-242ad0cb5cbe">

但是在 CloudFlare 和 Microsoft Clarity 统计的后台显示的数字都很正常。不明白这是什么原理，望大佬解惑。

此致。

---

As the title suggests.

I introduced JavaScript to my blog about half a mo ago without adding the HTML. When I built it locally today, I was shocked by the ridiculous statistics:

<img width="903" alt="image" src="https://github.com/EvanNotFound/vercount/assets/146422759/9ca2118b-efb7-4a9d-ba73-242ad0cb5cbe">

However, the numbers displayed in the backend statistics for CloudFlare and Microsoft Clarity were normal. I was quite confused about this phenomenon, that's why I'm bothering you.

Best regards.

**Comment by yoghurtlee-thu** [comment]
刚刚发布到 Vercel 试了一下，在生产环境下的数据似乎很正常。

**Comment by EvanNotFound** [comment]
额

Vercount 按照域名统计。

本地都是 localhost 或者 127.0.0.1。因为大家本地测试域名都是一样的，所以就都会统计进去。数据高是正常的。
